development:
  adapter: postgresql
  encoding: utf8
  database: foobar_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: foobar_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: foobar_production
  pool: 5

cucumber:
  <<: *TEST
